<?php
/* Internal function used in campusapp */
function campusapp_formatBizQueryParamMap($paramMap, $urlencode = false)
{
	$buff = "";
	foreach ($paramMap as $k => $v)
	{
		if ($v === "" || $v === null) continue;
		if($urlencode)
		{
		   $v = urlencode($v);
		}
		$buff .= $k . "=" . $v . "&";
	}
	$reqPar = '';
	if (strlen($buff) > 0)
	{
		$reqPar = substr($buff, 0, strlen($buff)-1);
	}
	return $reqPar;
}

function campusapp_getSign($Parameters, $key='')
{
	ksort($Parameters);
	$String = campusapp_formatBizQueryParamMap($Parameters, false);
	$String = $String."&key=".$key;
	$String = md5($String);
	$result = strtoupper($String);
	return $result;
}

/**
 * Implements hook_qyweixin_from_username_alter().
 */
function campusapp_qyweixin_from_username_alter(&$username) {
	$data=['userid'=>$username, 'source'=>\Drupal::config('campusapp.settings')->get('apisource')];
	$data['signature'] = campusapp_getSign($data, \Drupal::config('campusapp.settings')->get('apikey'));
	$url=sprintf('http://%s/api/user/toxgh', \Drupal::config('campusapp.settings')->get('host'));
	$data = (string) \Drupal::httpClient()->post($url, ['form_params'=>$data])->getBody();
	$result = json_decode($data);
	if(!property_exists($result,'e')) {
		\Drupal::logger('campusapp')->error('Error when accessing campusapp interface user/toxgh');
		return;
	}
	if($result->e=='9999') {
		if(is_array($result->data)) {
			$u=[];
			foreach($result->data as $r) {
				$u[]=$r->xgh;
			}
			$username=$u;
		}
		else 
			$username=$result->data->xgh;
	}
	else \Drupal::logger('campusapp')->error('Error when accessing campusapp interface user/toxgh: %errcode: %errmsg. Parameter: %param', ['%errcode'=>$result->e, '%errmsg'=>$result->m, '%param' =>$username]);
}

/**
 * Implements hook_qyweixin_to_username_alter().
 */
function campusapp_qyweixin_to_username_alter(&$username) {
	$data=['xgh'=>$username, 'source'=>\Drupal::config('campusapp.settings')->get('apisource')];
	$data['signature'] = campusapp_getSign($data, \Drupal::config('campusapp.settings')->get('apikey'));
	$url=sprintf('http://%s/api/user/detail', \Drupal::config('campusapp.settings')->get('host'));
	$data = (string) \Drupal::httpClient()->post($url, ['form_params'=>$data])->getBody();
	$result = json_decode($data);
	if(!property_exists($result,'e')) {
		\Drupal::logger('campusapp')->error('Error when accessing campusapp interface user/toxgh');
		return;
	}
	if($result->e=='9999') $username=$result->data->userid;
	else \Drupal::logger('campusapp')->error('Error when accessing campusapp interface user/detail: %errcode: %errmsg. Parameter: %param', ['%errcode'=>$result->e, '%errmsg'=>$result->m, '%param'=>$username]);
}

/**
 * Implements hook_library_info_alter().
 */
function campusapp_library_info_alter(&$libraries, $extension) {
	$host=\Drupal::config('campusapp.settings')->get('host');
	if(empty($host)) return;
	unset($libraries['campusapp-qrlogin']['js']);
	$libraries['campusapp-qrlogin']['js']=[
		'//'.$host.'/js/mxqrcode.js' => ['type' => 'external', 'minified' => 'true'],
		'//'.$host.'/js/mxsocket.js' => ['type' => 'external', 'minified' => 'true'],
		'js/init.js' => ''
	];
}

/**
 * Implements hook_page_attachments_alter().
 */
function campusapp_page_attachments_alter(&$page) {
	$host=\Drupal::config('campusapp.settings')->get('host');
	if(empty($host)) return;
	$page['#attached']['drupalSettings']['campusapp']['qrLogin']=[
		'host'=>($_SERVER['HTTPS']?'https://':'http://').$host,
		'posturl'=>\Drupal\Core\Url::fromRoute('campusapp.qrcodelogin', [], ['absolute'=>TRUE])->toString(),
		//'posturl'=>'http://api.library.ccom.edu.cn/return.php',
		'apisource'=>\Drupal::config('campusapp.settings')->get('apisource'),
		'pagetitle'=>t('Login @site_name', ['@site_name'=>\Drupal::config('system.site')->get('name')]),
		'sessionid'=>\Drupal::service('session')->getId()
	];
}

?>
